### ISSUE TITLE
Another FFT bug

### ISSUE THREAD

**Issue by leto** [leto/math--gsl#132]
The function `gsl_fft_real_transform` is causing core dumps. Rarely on OS X, but every time on Travis CI. On OS X the backtrace from the coredump looks like:

```
(lldb) bt
* thread #1: tid = 0x0000, 0x00000001053c8297 libperl.dylib`___lldb_unnamed_function156$$libperl.dylib + 37, stop reason = signal SIGSTOP
  * frame #0: 0x00000001053c8297 libperl.dylib`___lldb_unnamed_function156$$libperl.dylib + 37
    frame #1: 0x00000001053c81c0 libperl.dylib`___lldb_unnamed_function154$$libperl.dylib + 93
    frame #2: 0x00000001053c8086 libperl.dylib`Perl_sv_clean_objs + 64
    frame #3: 0x0000000105353bb4 libperl.dylib`perl_destruct + 495
    frame #4: 0x0000000105331d35 perl5.18`main + 309
    frame #5: 0x00007fff92c3c5c9 libdyld.dylib`start + 1
(lldb) register read
General Purpose Registers:
       rax = 0x00007fb88357f5e0
       rbx = 0x00007fb8839a6248
       rcx = 0x00007fb8839a6230
       rdx = 0x0000000000000009
       rdi = 0x00007fb884800400
       rsi = 0x4008000000000000
       rbp = 0x00007fff5a8cded0
       rsp = 0x00007fff5a8cdec0
        r8 = 0x0000000000000001
        r9 = 0x00007fb883700000
       r10 = 0x0000000000000020
       r11 = 0x00007fb883700000
       r12 = 0x00007fb8839a6248
       r13 = 0x00007fb8839a5600
       r14 = 0x00007fb884800400
       r15 = 0x000000000000c0ff
       rip = 0x00000001053c8297  libperl.dylib`___lldb_unnamed_function156$$libperl.dylib + 37
    rflags = 0x0000000000010206
        cs = 0x000000000000002b
        fs = 0x0000000000000000
        gs = 0x0000000000000000
```

All the tests pass but something happens when Perl is cleaning up memory on OS X and the test file bails out with:
```
t/FFT.t .. All 30 subtests passed

Test Summary Report
-------------------
t/FFT.t (Wstat: 139 Tests: 30 Failed: 0)
  Non-zero wait status: 139
```.
 On Travis CI, the tests coredump and stop right after `gsl_fft_real_transform` is called.

**Comment by leto** [comment]
Just got a backtrace from Travis CI:

```
[Thread debugging using libthread_db enabled]
Using host libthread_db library "/lib/x86_64-linux-gnu/libthread_db.so.1".
Core was generated by `/home/travis/perl5/perlbrew/perls/5.24/bin/perl t/FFT.t'.
Program terminated with signal SIGSEGV, Segmentation fault.
#0  0x00000000004ba2cc in S_sv_unmagicext_flags.part.9 ()

Thread 1 (Thread 0x7facd1e4f740 (LWP 9670)):
#0  0x00000000004ba2cc in S_sv_unmagicext_flags.part.9 ()
#1  0x00000000004ba44d in Perl_sv_unmagic ()
#2  0x00000000004b95ec in Perl_sv_clear ()
#3  0x00000000004b9e69 in Perl_sv_free2 ()
#4  0x00000000004df436 in Perl_free_tmps ()
#5  0x00000000004addc5 in Perl_pp_nextstate ()
#6  0x00000000004adba3 in Perl_runops_standard ()
#7  0x00000000004416c0 in perl_run ()
#8  0x000000000041fe85 in main ()
```

at the very end of https://s3.amazonaws.com/archive.travis-ci.org/jobs/165995543/log.txt

**Comment by leto** [comment]
This is Perl 5.24 and GSL 1.15:
```
[Thread debugging using libthread_db enabled]
Using host libthread_db library "/lib/x86_64-linux-gnu/libthread_db.so.1".
Core was generated by `/home/travis/perl5/perlbrew/perls/5.24/bin/perl t/FFT.t'.
Program terminated with signal SIGSEGV, Segmentation fault.
#0  0x00000000004a6a28 in S_share_hek_flags ()

Thread 1 (Thread 0x7f79ff3f0740 (LWP 9599)):
#0  0x00000000004a6a28 in S_share_hek_flags ()
#1  0x00000000004a8110 in Perl_share_hek ()
#2  0x0000000000442571 in Perl_gv_name_set ()
#3  0x00000000004426b6 in Perl_gv_init_pvn ()
#4  0x00007f79fce8159a in XS_Sub__Util_set_subname () from /home/travis/perl5/perlbrew/perls/5.24/lib/site_perl/5.24.0/x86_64-linux/auto/List/Util/Util.so
#5  0x00000000004b4d2c in Perl_pp_entersub ()
#6  0x00000000004adba3 in Perl_runops_standard ()
#7  0x00000000004416c0 in perl_run ()
#8  0x000000000041fe85 in main ()
```

**Comment by leto** [comment]
```
[Thread debugging using libthread_db enabled]
Using host libthread_db library "/lib/x86_64-linux-gnu/libthread_db.so.1".
Core was generated by `/home/travis/perl5/perlbrew/perls/5.16/bin/perl t/FFT.t'.
Program terminated with signal SIGSEGV, Segmentation fault.
#0  0x000000000048b728 in S_share_hek_flags ()

Thread 1 (Thread 0x7ff1d5f53740 (LWP 9667)):
#0  0x000000000048b728 in S_share_hek_flags ()
#1  0x000000000048b850 in Perl_share_hek ()
#2  0x000000000043bc52 in Perl_gv_name_set ()
#3  0x000000000043bd8a in Perl_gv_init_pvn ()
#4  0x00007ff1d3c092ed in XS_Sub__Name_subname () from /home/travis/perl5/perlbrew/perls/5.16/lib/site_perl/5.16.3/x86_64-linux/auto/Sub/Name/Name.so
#5  0x0000000000497bcd in Perl_pp_entersub ()
#6  0x0000000000490b43 in Perl_runops_standard ()
#7  0x000000000043982e in perl_run ()
#8  0x000000000041f42d in main ()
```
Perl 5.16, GSL 2.1
